### ISSUE TITLE
polys is not defined error in strict mode

### ISSUE THREAD

**Issue by jcphill** [GeoTIFF/dufour-peyton-intersection#4]
https://github.com/GeoTIFF/dufour-peyton-intersection/blob/f38f16ce87d71be685a46f399847ee5cd96f69a1/src/calculate.js#L7

**Comment by DanielJDufour** [comment]
great catch. I'm on it.

**Comment by DanielJDufour** [comment]
this issue with dufour-peyton-intersection should be fixed now
